### ISSUE TITLE
save weight and kernel of cnn

### ISSUE THREAD

**Issue by kaikai529** [Hattomo/kaikai_AI#166] opened 2020-11-20 12:49 UTC
## Description
According to initial value of weight and kernel , CNN can learn training data.
So we choose initial value of weight and kernel and restart learning them.
## Check list 
- [ ] Save kernel
- [ ] Save weight
- [ ] set kernel
- [ ] set weight

**Comment by Hattomo** [comment] 2020-11-20 16:02
Duplicate of #159

**Closed as completed by Hattomo** 2020-11-20 16:02 UTC
Labels: Duplicate
